
env:
   global:
     - CONAN_REFERENCE: "XmpSdk/2016.7"
     - CONAN_USERNAME: "piponazo"
     - CONAN_LOGIN_USERNAME: "piponazo"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/piponazo/piponazo"
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

        #- <<: *linux
        #env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39

        #- <<: *linux
        #env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40

        #- <<: *osx
        #- osx_image: xcode7.3
        #- env: CONAN_APPLE_CLANG_VERSIONS=7.3 XMP_OSX_SDK=10.11 MACOSX_DEPLOYMENT_TARGET=10.11

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 XMP_OSX_SDK=10.12 MACOSX_DEPLOYMENT_TARGET=10.12

        #- <<: *osx
        #- osx_image: xcode9.2
        #- env: CONAN_APPLE_CLANG_VERSIONS=9.0 XMP_OSX_SDK=10.13 MACOSX_DEPLOYMENT_TARGET=10.13

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
